[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"

rustflags = [
 "-C", "link-arg=--nmagic",
 "-C", "link-arg=-Tlink.x",
 "-C", "link-arg=-Tdefmt.x",
 "-C", "inline-threshold=5",
 "-C", "no-vectorize-loops",
 "-C", "link-args=--print-memory-usage",
 "-C", "link-args=-Map=target/led_blink.map",
]

[env]
DEFMT_LOG = "debug"
